name: SimpleTrading
main: me.traox.tradeplugin.Events
description: Simple Trading
version: '1.3.1'
author: TraoX
depend: [ProtocolLib, Vault]
softdepend: []

commands:
  trade:
    description: Sends a trade to a player
    usage: /trade
    aliases: [trade]
  toggletrading:
    description: disables/enables the ability for players to trade
    usage: /toggletrading
    aliases: [toggletrading]
  edittrade:
    description: allows you to edit the trade menu
    usage: /edittrade
    aliases: [edittrade]
  blacklisttradeslot:
    description: adds a specific slot in your inventory to the trade blacklist.
    usage: /blacklisttradeslot
    aliases: [blacklisttradeslot]

permissions:
  tradeplugin.use.toggletrading:
    description: permission to use /toggletrading
    default: op
  tradeplugin.use.edittrade:
    description: permission to use /toggletrading
    default: op
  tradeplugin.use.blacklisttradeslot:
    description: permission to use /blacklisttradeslot
    default: op